### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by dry** [230delphi/hassio-addons#3]
I still need some help in configuring this addon. Here is my current config

![image](https://user-images.githubusercontent.com/342807/140652489-701cbba0-5666-4c63-8da9-97f2b280d099.png)

I have set the gateway to be my HA Pi and therefore I've set the ProxyPort to be 7777. I don't see any data being received. Is this a correct configuration?

**Comment by 230delphi** [comment]
If you've set the gateway to be the pi (not the server) you'll still need to enable routing on the box with something like:
`sudo sysctl -w net.ipv4.conf.all.route_localnet=1`
But I haven't tried it myself with this config...

**Comment by 230delphi** [comment]
I've added a direct proxy config option - to see it you need to reload your appstore, then uninstall and reinstall the addon. you can now configure the destination ip: this should allow you simply configure the server ip (instead of the gateway) on the alpha to your HA proxy; you won't need to muck with routing or ip tables. I hope to test this out in my environment later this week.

**Comment by dry** [comment]
Ah, great. Thanks, I'll try this out.

**Comment by 230delphi** [comment]
I hope this one is now working for you..
